name: HIPTrack
channels:
  - pytorch
  - nvidia
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - argon2-cffi=21.3.0=pyhd8ed1ab_0
  - argon2-cffi-bindings=21.2.0=py38h0a891b7_2
  - asttokens=2.0.5=pyhd8ed1ab_0
  - attrs=21.4.0=pyhd8ed1ab_0
  - backcall=0.2.0=pyh9f0ad1d_0
  - backports=1.0=py_2
  - backports.functools_lru_cache=1.6.4=pyhd8ed1ab_0
  - beautifulsoup4=4.11.1=pyha770c72_0
  - blas=1.0=mkl
  - bleach=5.0.0=pyhd8ed1ab_0
  - brotlipy=0.7.0=py38h0a891b7_1004
  - bzip2=1.0.8=h7f98852_4
  - ca-certificates=2025.4.26=hbd8a1cb_0
  - certifi=2024.8.30=pyhd8ed1ab_0
  - cffi=1.15.0=py38h7f8727e_0
  - charset-normalizer=2.0.12=pyhd8ed1ab_0
  - cryptography=37.0.2=py38h2b5fc30_0
  - cuda-cccl=12.4.127=0
  - cuda-command-line-tools=12.4.1=0
  - cuda-compiler=12.6.2=0
  - cuda-cudart=12.4.127=0
  - cuda-cudart-dev=12.4.127=0
  - cuda-cudart-static=12.4.127=0
  - cuda-cuobjdump=12.4.127=0
  - cuda-cupti=12.4.127=0
  - cuda-cupti-static=12.4.127=0
  - cuda-cuxxfilt=12.4.127=0
  - cuda-documentation=12.4.127=0
  - cuda-driver-dev=12.4.127=0
  - cuda-gdb=12.4.127=0
  - cuda-libraries=12.6.2=0
  - cuda-libraries-dev=12.6.0=0
  - cuda-libraries-static=12.4.1=0
  - cuda-nsight=12.4.127=0
  - cuda-nvcc=12.4.131=0
  - cuda-nvdisasm=12.4.127=0
  - cuda-nvml-dev=12.4.127=0
  - cuda-nvprof=12.4.127=0
  - cuda-nvprune=12.4.127=0
  - cuda-nvrtc=12.4.127=0
  - cuda-nvrtc-dev=12.4.127=0
  - cuda-nvrtc-static=12.4.127=0
  - cuda-nvtx=12.4.127=0
  - cuda-nvvp=12.4.127=0
  - cuda-opencl=12.4.127=0
  - cuda-opencl-dev=12.4.127=0
  - cuda-profiler-api=12.4.127=0
  - cuda-sanitizer-api=12.4.127=0
  - cuda-toolkit=12.4.1=0
  - cuda-tools=12.4.1=0
  - cuda-visual-tools=12.6.0=0
  - cudatoolkit=11.3.1=hb98b00a_12
  - dbus=1.13.18=hb2f20db_0
  - debugpy=1.6.0=py38hfa26641_0
  - defusedxml=0.7.1=pyhd8ed1ab_0
  - entrypoints=0.4=pyhd8ed1ab_0
  - executing=0.8.3=pyhd8ed1ab_0
  - expat=2.4.8=h27087fc_0
  - ffmpeg=4.3=hf484d3e_0
  - flit-core=3.7.1=pyhd8ed1ab_0
  - fontconfig=2.14.0=h8e229c2_0
  - freetype=2.10.4=h0708190_1
  - gds-tools=1.9.1.3=0
  - gettext=0.19.8.1=hf34092f_1004
  - giflib=5.2.1=h36c2ea0_2
  - glib=2.58.3=py38h73cb85d_1004
  - gmp=6.2.1=h58526e2_0
  - gnutls=3.6.13=h85f3911_1
  - gst-plugins-base=1.14.0=hbbd80ab_1
  - gstreamer=1.14.0=hb453b48_1
  - icu=58.2=hf484d3e_1000
  - idna=3.3=pyhd8ed1ab_0
  - importlib-metadata=4.11.4=py38h578d9bd_0
  - importlib_resources=5.7.1=pyhd8ed1ab_1
  - intel-openmp=2021.4.0=h06a4308_3561
  - ipykernel=6.13.0=py38h7f3c49e_0
  - ipython=8.4.0=py38h578d9bd_0
  - ipython_genutils=0.2.0=py_1
  - ipywidgets=7.7.0=pyhd8ed1ab_0
  - jedi=0.18.1=py38h578d9bd_1
  - jinja2=3.1.2=pyhd8ed1ab_0
  - jpeg=9e=h166bdaf_1
  - jsonschema=4.6.0=pyhd8ed1ab_0
  - jupyter=1.0.0=py38h578d9bd_7
  - jupyter_client=7.3.1=pyhd8ed1ab_0
  - jupyter_console=6.4.3=pyhd8ed1ab_0
  - jupyter_core=4.10.0=py38h578d9bd_0
  - jupyterlab_pygments=0.2.2=pyhd8ed1ab_0
  - jupyterlab_widgets=1.1.0=pyhd8ed1ab_0
  - lame=3.100=h7f98852_1001
  - lcms2=2.12=hddcbb42_0
  - ld_impl_linux-64=2.36.1=hea4e1c9_2
  - lerc=3.0=h9c3ff4c_0
  - libcublas=12.4.5.8=0
  - libcublas-dev=12.4.5.8=0
  - libcublas-static=12.4.5.8=0
  - libcufft=11.2.1.3=0
  - libcufft-dev=11.2.1.3=0
  - libcufft-static=11.2.1.3=0
  - libcufile=1.9.1.3=0
  - libcufile-dev=1.9.1.3=0
  - libcufile-static=1.9.1.3=0
  - libcurand=10.3.5.147=0
  - libcurand-dev=10.3.5.147=0
  - libcurand-static=10.3.5.147=0
  - libcusolver=11.6.1.9=0
  - libcusolver-dev=11.6.1.9=0
  - libcusolver-static=11.6.1.9=0
  - libcusparse=12.3.1.170=0
  - libcusparse-dev=12.3.1.170=0
  - libcusparse-static=12.3.1.170=0
  - libdeflate=1.10=h7f98852_0
  - libffi=3.2.1=he1b5a44_1007
  - libgcc-ng=12.1.0=h8d9b700_16
  - libgomp=12.1.0=h8d9b700_16
  - libiconv=1.16=h516909a_0
  - libnpp=12.2.5.30=0
  - libnpp-dev=12.2.5.30=0
  - libnpp-static=12.2.5.30=0
  - libnvfatbin=12.4.127=0
  - libnvfatbin-dev=12.4.127=0
  - libnvjitlink=12.4.127=0
  - libnvjitlink-dev=12.4.127=0
  - libnvjpeg=12.3.1.117=0
  - libnvjpeg-dev=12.3.1.117=0
  - libnvjpeg-static=12.3.1.117=0
  - libpng=1.6.37=h21135ba_2
  - libsodium=1.0.18=h36c2ea0_1
  - libstdcxx-ng=13.2.0=hc0a3c3a_7
  - libtiff=4.4.0=h0fcbabc_0
  - libuuid=2.32.1=h7f98852_1000
  - libuv=1.43.0=h7f98852_0
  - libwebp=1.2.2=h3452ae3_0
  - libwebp-base=1.2.2=h7f98852_1
  - libxcb=1.13=h7f98852_1004
  - libxml2=2.9.14=h74e7548_0
  - libzlib=1.2.12=h166bdaf_0
  - lz4-c=1.9.3=h9c3ff4c_1
  - markupsafe=2.1.1=py38h0a891b7_1
  - matplotlib-inline=0.1.3=pyhd8ed1ab_0
  - mistune=0.8.4=py38h497a2fe_1005
  - mkl=2021.4.0=h06a4308_640
  - mkl-service=2.4.0=py38h95df7f1_0
  - mkl_fft=1.3.1=py38h8666266_1
  - mkl_random=1.2.2=py38h1abd341_0
  - nbclient=0.6.4=pyhd8ed1ab_1
  - nbconvert=6.5.0=pyhd8ed1ab_0
  - nbconvert-core=6.5.0=pyhd8ed1ab_0
  - nbconvert-pandoc=6.5.0=pyhd8ed1ab_0
  - nbformat=5.4.0=pyhd8ed1ab_0
  - ncurses=6.3=h27087fc_1
  - nest-asyncio=1.5.5=pyhd8ed1ab_0
  - nettle=3.6=he412f7d_0
  - notebook=6.4.11=pyha770c72_0
  - nsight-compute=2024.1.1.4=0
  - openh264=2.1.1=h780b84a_0
  - openjpeg=2.4.0=hb52868f_1
  - openssl=1.1.1w=hd590300_0
  - packaging=21.3=pyhd8ed1ab_0
  - pandoc=2.18=ha770c72_0
  - pandocfilters=1.5.0=pyhd8ed1ab_0
  - parso=0.8.3=pyhd8ed1ab_0
  - pcre=8.45=h9c3ff4c_0
  - pexpect=4.8.0=pyh9f0ad1d_2
  - pickleshare=0.7.5=py_1003
  - pillow=9.1.1=py38h0ee0e06_1
  - prometheus_client=0.14.1=pyhd8ed1ab_0
  - prompt-toolkit=3.0.29=pyha770c72_0
  - prompt_toolkit=3.0.29=hd8ed1ab_0
  - psutil=5.9.1=py38h0a891b7_0
  - pthread-stubs=0.4=h36c2ea0_1001
  - ptyprocess=0.7.0=pyhd3deb0d_0
  - pure_eval=0.2.2=pyhd8ed1ab_0
  - pycparser=2.21=pyhd8ed1ab_0
  - pyopenssl=22.0.0=pyhd8ed1ab_0
  - pyqt=5.9.2=py38h05f1152_4
  - pyrsistent=0.18.1=py38h0a891b7_1
  - pysocks=1.7.1=py38h578d9bd_5
  - python=3.8.6=h852b56e_0_cpython
  - python-dateutil=2.8.2=pyhd8ed1ab_0
  - python-fastjsonschema=2.15.3=pyhd8ed1ab_0
  - python_abi=3.8=2_cp38
  - pytorch-mutex=1.0=cuda
  - pyzmq=23.1.0=py38hfc09fa9_0
  - qt=5.9.7=h5867ecd_1
  - qtconsole=5.3.0=pyhd8ed1ab_0
  - qtconsole-base=5.3.0=pyha770c72_0
  - qtpy=2.1.0=pyhd8ed1ab_0
  - readline=8.1=h46c0cb4_0
  - send2trash=1.8.0=pyhd8ed1ab_0
  - sip=4.19.13=py38h295c915_0
  - six=1.16.0=pyh6c4a22f_0
  - soupsieve=2.3.1=pyhd8ed1ab_0
  - sqlite=3.38.5=h4ff8645_0
  - stack_data=0.2.0=pyhd8ed1ab_0
  - terminado=0.15.0=py38h578d9bd_0
  - tinycss2=1.1.1=pyhd8ed1ab_0
  - tk=8.6.12=h27826a3_0
  - tornado=6.1=py38h0a891b7_3
  - traitlets=5.2.2.post1=pyhd8ed1ab_0
  - urllib3=1.26.9=pyhd8ed1ab_0
  - wcwidth=0.2.13=pyhd8ed1ab_0
  - webencodings=0.5.1=py_1
  - wheel=0.37.1=pyhd8ed1ab_0
  - widgetsnbextension=3.6.0=py38h578d9bd_0
  - xorg-libxau=1.0.9=h7f98852_0
  - xorg-libxdmcp=1.1.3=h7f98852_0
  - xz=5.2.5=h516909a_1
  - zeromq=4.3.4=h9c3ff4c_1
  - zipp=3.8.0=pyhd8ed1ab_0
  - zlib=1.2.12=h166bdaf_0
  - zstd=1.5.2=h8a70e8d_1
  - pip:
      - absl-py==1.1.0
      - addict==2.4.0
      - albucore==0.0.17
      - albumentations==1.4.18
      - aliyun-python-sdk-core==2.14.0
      - aliyun-python-sdk-kms==2.16.2
      - annotated-types==0.7.0
      - antlr4-python3-runtime==4.9.3
      - appdirs==1.4.4
      - astroid==2.12.5
      - attributee==0.1.8
      - audioread==3.0.1
      - auraloss==0.4.0
      - autoflake==2.0.1
      - backports-tarfile==1.2.0
      - basecore==0.1.9
      - bcrypt==4.3.0
      - bidict==0.22.1
      - black==21.4b2
      - boto3==1.24.42
      - botocore==1.27.42
      - cachetools==5.2.0
      - cityscapesscripts==2.2.0
      - click==8.1.3
      - clip==0.2.0
      - cloudpickle==2.1.0
      - colorama==0.4.4
      - coloredlogs==15.0.1
      - commonmark==0.9.1
      - contourpy==1.1.1
      - crc32c==2.3
      - crcmod==1.7
      - cycler==0.11.0
      - cython==0.29.30
      - decorator==4.4.2
      - deprecated==1.2.18
      - diffdist==0.1
      - dill==0.3.5.1
      - docker-pycreds==0.4.0
      - dominate==2.8.0
      - easydict==1.9
      - einops==0.7.0
      - et-xmlfile==1.1.0
      - eval-type-backport==0.2.2
      - fairscale==0.4.6
      - faiss-cpu==1.7.2
      - filelock==3.16.1
      - filterpy==1.4.5
      - flatbuffers==2.0
      - fonttools==4.33.3
      - fsspec==2023.10.0
      - ftfy==6.1.3
      - future==0.18.2
      - fvcore==0.1.5.post20220512
      - gevent==23.9.1
      - gitdb==4.0.9
      - gitpython==3.1.27
      - google-auth==2.23.4
      - google-auth-oauthlib==0.4.6
      - greenlet==3.0.1
      - grpcio==1.59.2
      - h5py==3.7.0
      - hf-xet==1.2.0
      - huggingface-hub==0.36.0
      - humanfriendly==10.0
      - hydra-core==1.2.0
      - imageio==2.35.1
      - imageio-ffmpeg==0.4.7
      - iopath==0.1.9
      - isort==5.10.1
      - jmespath==0.10.0
      - joblib==1.4.2
      - jpeg4py==0.1.4
      - jsonpatch==1.32
      - jsonpointer==2.2
      - kiwisolver==1.4.2
      - lazy-loader==0.4
      - lazy-object-proxy==1.9.0
      - librosa==0.8.1
      - llvmlite==0.39.0
      - lmdb==1.3.0
      - loguru==0.6.0
      - markdown==3.7
      - markdown-it-py==3.0.0
      - matplotlib==3.5.2
      - mccabe==0.7.0
      - mdurl==0.1.2
      - megengine==1.13.0
      - megfile==2.0.5
      - memory-profiler==0.61.0
      - mmdet==2.28.1
      - model-index==0.1.11
      - motmetrics==1.2.5
      - moviepy==0.2.3.5
      - mpmath==1.2.1
      - mprop==0.17.0
      - mypy-extensions==0.4.3
      - natsort==8.1.0
      - networkx==2.8.2
      - ninja==1.10.2.3
      - numba==0.56.0
      - numpy==1.24.4
      - nvidia-cublas-cu12==12.1.3.1
      - nvidia-cuda-cupti-cu12==12.1.105
      - nvidia-cuda-nvrtc-cu12==12.1.105
      - nvidia-cuda-runtime-cu12==12.1.105
      - nvidia-cudnn-cu12==8.9.2.26
      - nvidia-cufft-cu12==11.0.2.54
      - nvidia-curand-cu12==10.3.2.106
      - nvidia-cusolver-cu12==11.4.5.107
      - nvidia-cusparse-cu12==12.1.0.106
      - nvidia-nccl-cu12==2.19.3
      - nvidia-nvjitlink-cu12==12.1.105
      - nvidia-nvtx-cu12==12.1.105
      - oauthlib==3.2.0
      - omegaconf==2.2.2
      - onnx==1.12.0
      - onnx-simplifier==0.4.5
      - onnxoptimizer==0.2.7
      - onnxruntime==1.12.1
      - opencv-python==4.5.5.64
      - opencv-python-headless==4.12.0.88
      - openmim==0.3.5
      - openpyxl==3.0.10
      - openxlab==0.0.33
      - ordered-set==4.1.0
      - oss2==2.17.0
      - pandas==1.4.2
      - paramiko==3.5.1
      - pathspec==0.9.0
      - pathtools==0.1.2
      - phx-class-registry==4.0.6
      - pip==25.0.1
      - platformdirs==2.5.2
      - pooch==1.8.0
      - portalocker==2.5.1
      - prettytable==3.3.0
      - progressbar==2.5
      - promise==2.3
      - protobuf==3.20.1
      - pyarrow==11.0.0
      - pyasn1==0.4.8
      - pyasn1-modules==0.2.8
      - pycocotools==2.0.7
      - pycryptodome==3.19.1
      - pydantic==2.10.6
      - pydantic-core==2.27.2
      - pydot==1.4.2
      - pyflakes==3.0.1
      - pygments==2.17.2
      - pylatex==1.4.2
      - pylint==2.15.0
      - pynacl==1.5.0
      - pyparsing==3.1.1
      - pyqt5==5.15.4
      - pyqt5-qt5==5.15.2
      - pyqt5-sip==12.11.0
      - pyquaternion==0.9.9
      - python-xlib==0.31
      - pytz==2023.3.post1
      - pywavelets==1.3.0
      - pyyaml==6.0.2
      - regex==2024.11.6
      - requests==2.32.4
      - requests-oauthlib==1.3.1
      - resampy==0.4.2
      - rich==13.4.2
      - rsa==4.8
      - s3transfer==0.6.0
      - safetensors==0.5.3
      - scikit-image==0.21.0
      - scikit-learn==1.3.2
      - scipy==1.10.1
      - seaborn==0.11.2
      - sentry-sdk==1.6.0
      - setproctitle==1.2.3
      - setuptools==60.2.0
      - shapely==1.7.0
      - shortuuid==1.0.9
      - smmap==5.0.0
      - soundfile==0.13.1
      - sympy==1.10.1
      - tabulate==0.8.9
      - tensorboard==2.9.0
      - tensorboard-data-server==0.7.2
      - tensorboard-plugin-wit==1.8.1
      - tensorboardx==2.5.1
      - termcolor==1.1.0
      - terminaltables==3.1.10
      - thop==0.1.1-2209072238
      - threadpoolctl==3.1.0
      - tifffile==2023.7.10
      - tikzplotlib==0.10.1
      - timm==1.0.3
      - tokenizers==0.20.3
      - toml==0.10.2
      - tomli==2.0.1
      - tomlkit==0.11.4
      - torch==2.2.1+cu121
      - torch-ema==0.3
      - torch-summary==1.4.5
      - torchaudio==2.2.1+cu121
      - torchfile==0.1.0
      - torchstat==0.0.7
      - torchvision==0.17.1+cu121
      - tqdm==4.65.2
      - transformers==4.46.3
      - triton==2.2.0
      - typing==3.7.4.3
      - typing-extensions==4.12.2
      - tzdata==2023.3
      - visdom==0.1.8.9
      - vot-toolkit==0.6.4
      - vot-trax==4.0.2
      - wandb==0.12.20
      - webcolors==1.12
      - websocket==0.2.1
      - websocket-client==1.3.2
      - werkzeug==2.1.2
      - wget==3.2
      - wrapt==1.14.1
      - xmltodict==0.13.0
      - yacs==0.1.8
      - yapf==0.32.0
      - youtube-dl==2021.12.17
      - zope-event==5.0
      - zope-interface==6.1
prefix: /data/ruanjian/anaconda3/envs/HIPTrack
